# fly.toml app configuration file generated for server-phonebook on 2024-11-29T10:18:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-phonebook'
primary_region = 'arn'

[build]

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1